# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e96bf109b015206c9670c981d193cd208d1598f0722d9f05052580ec46107f450279ad704798871fc6d748e60c5fb6a4253800703c5f24e51aa89941d8b42b96

test:
  secret_key_base: 7427fb0e5872fafeac56d301f38a979fe9b44e01a6ae171c5b8b587900147c99fce08575355fe7323e3bbb69342e96f0367a5ec8c5cf449b715dbe98d58f6964

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
